---
title: "eco-evolutionary models"
author: "Ben Bolker"
---

## what are eco-evolutionary models?

- Hutchinson: evolutionary theater, ecological play  
(i.e. ecological rates $\gg$ evolutionary rates)
- what if the rates are similar?
    - ecological dynamics (e.g. logistic equation)
    - evolutionary dynamics (changes in traits)
- alternatively, population genetics plus population dynamics

## why aren't all models like this?

- eco/evo time scales are often different
- it's hard!
    - most population genetic models assume constant population size
    - most ecological models assume constant traits

## how do we do it?

- range of realism/complexity
- individual or agent-based models
    - each individual has a genotype and a phenotype
    - rules for life history and interactions
- models for the distribution of a continuous trait
    - partial differential equations
    - reaction-diffusion equations
	- includes demography, mutation
- moment equations
    - simplify PDEs to equations for the means and variances of traits, plus population densities
- Price equations:
    - further simplify to equations for the means of traits (assume constant variance)

## individual-based models

- maximum detail

## population-based models

## distribution models

## moment equations

## Price equations



## PDE basics

